# Generated by Django 4.1.3 on 2023-12-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('Administrator', 'Administrator')], max_length=30, null=True),
        ),
    ]
