# Generated by Django 3.2.8 on 2024-01-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Administrator', 'Administrator')], max_length=30, null=True),
        ),
    ]
